### ISSUE TITLE
BetterDiscord fails to load the plugin.

### ISSUE THREAD

**Issue by alba4k** [ImTheSquid/Tuxphones#14] opened 2022-11-20 17:26 UTC
I know this isn't much, but betterdiscord simply fails to load the plugin.

![immagine](https://user-images.githubusercontent.com/84153269/202916502-31bd3983-879a-4d0e-9d4a-dbec3a5f50e6.png)
![immagine](https://user-images.githubusercontent.com/84153269/202916525-ded95a45-f235-4420-9a04-d6e124145bb7.png)
![immagine](https://user-images.githubusercontent.com/84153269/202916532-c716071b-9287-4e6a-beaa-c6807e298951.png)

I don't have any other plugins installed, just a custom css

Is there any way I can be helpful?

**Comment by ImTheSquid** [comment] 2022-11-21 15:48
This is a duplicate of #13, I'm currently waiting for my partner to get back into this project since if I work on this and he doesn't, the plugin still won't work.

**Closed by ImTheSquid** 2022-11-21 15:48 UTC
